export enum BlockType {
  // Existing
  AIR=0, GRASS=1, DIRT=2, STONE=3, BEDROCK=4,
  WOOD=5, LEAF=6, SAND=7, WATER=8, COAL_ORE=9,
  IRON_ORE=10, GLASS=11, PLANKS=12, COBBLESTONE=13, TNT=14,

  // Stone variants
  GRANITE=15, GRANITE_SMOOTH=16, DIORITE=17, DIORITE_SMOOTH=18,
  ANDESITE=19, ANDESITE_SMOOTH=20, DEEPSLATE=21, COBBLED_DEEPSLATE=22,
  TUFF=23, CALCITE=24, SMOOTH_STONE=25,

  // Stone bricks
  STONE_BRICKS=26, MOSSY_STONE_BRICKS=27, CRACKED_STONE_BRICKS=28,
  CHISELED_STONE_BRICKS=29, BRICKS=30, MOSSY_COBBLESTONE=31,
  POLISHED_GRANITE=32, POLISHED_DIORITE=33, POLISHED_ANDESITE=34,

  // Wood logs
  OAK_LOG=35, BIRCH_LOG=36, SPRUCE_LOG=37, DARK_OAK_LOG=38,
  JUNGLE_LOG=39, ACACIA_LOG=40, STRIPPED_OAK_LOG=41, BAMBOO_BLOCK=42,

  // Wood planks
  BIRCH_PLANKS=43, SPRUCE_PLANKS=44, DARK_OAK_PLANKS=45,
  JUNGLE_PLANKS=46, ACACIA_PLANKS=47, BAMBOO_PLANKS=48,

  // Leaves
  BIRCH_LEAF=49, SPRUCE_LEAF=50, DARK_OAK_LEAF=51,
  JUNGLE_LEAF=52, ACACIA_LEAF=53, AZALEA_LEAF=54,

  // Ores
  GOLD_ORE=55, DIAMOND_ORE=56, EMERALD_ORE=57, LAPIS_ORE=58,
  REDSTONE_ORE=59, COPPER_ORE=60, ANCIENT_DEBRIS=61,
  DIAMOND_DEEPSLATE=62, GOLD_DEEPSLATE=63,

  // Mineral blocks
  IRON_BLOCK=64, GOLD_BLOCK=65, DIAMOND_BLOCK=66, EMERALD_BLOCK=67,
  COPPER_BLOCK=68, COAL_BLOCK=69, LAPIS_BLOCK=70, REDSTONE_BLOCK=71,
  AMETHYST_BLOCK=72, RAW_IRON_BLOCK=73, RAW_GOLD_BLOCK=74,
  RAW_COPPER_BLOCK=75, NETHERITE_BLOCK=76, QUARTZ_BLOCK=77,

  // Soil
  GRAVEL=78, CLAY=79, MUD=80, PODZOL=81, MYCELIUM=82,
  COARSE_DIRT=83, ROOTED_DIRT=84, SOUL_SOIL=85, MOSS_BLOCK=86,

  // Sandstone
  SANDSTONE=87, SANDSTONE_SMOOTH=88, SANDSTONE_CHISELED=89,
  RED_SAND=90, RED_SANDSTONE=91, RED_SANDSTONE_SMOOTH=92,

  // Terracotta
  TERRACOTTA=93, WHITE_TERRACOTTA=94, ORANGE_TERRACOTTA=95,
  YELLOW_TERRACOTTA=96, RED_TERRACOTTA=97, BROWN_TERRACOTTA=98,
  GRAY_TERRACOTTA=99, CYAN_TERRACOTTA=100,

  // Ice & Snow
  ICE=101, PACKED_ICE=102, BLUE_ICE=103, SNOW_BLOCK=104,

  // Nether
  NETHERRACK=105, SOUL_SAND=106, GLOWSTONE=107, NETHER_BRICKS=108,
  RED_NETHER_BRICKS=109, BASALT=110, BLACKSTONE=111, MAGMA=112,
  CRYING_OBSIDIAN=113, NYLIUM_WARPED=114, NYLIUM_CRIMSON=115,
  NETHER_WART_BLOCK=116,

  // Nether wood
  WARPED_STEM=117, CRIMSON_STEM=118, WARPED_PLANKS=119,
  CRIMSON_PLANKS=120, SHROOMLIGHT=121,

  // End
  END_STONE=122, END_STONE_BRICKS=123, PURPUR_BLOCK=124,
  PURPUR_PILLAR=125, OBSIDIAN=126,

  // Concrete (15 colors)
  WHITE_CONCRETE=127, ORANGE_CONCRETE=128, MAGENTA_CONCRETE=129,
  LIGHT_BLUE_CONCRETE=130, YELLOW_CONCRETE=131, LIME_CONCRETE=132,
  PINK_CONCRETE=133, GRAY_CONCRETE=134, CYAN_CONCRETE=135,
  PURPLE_CONCRETE=136, BLUE_CONCRETE=137, BROWN_CONCRETE=138,
  GREEN_CONCRETE=139, RED_CONCRETE=140, BLACK_CONCRETE=141,

  // Wool (10 colors)
  WHITE_WOOL=142, ORANGE_WOOL=143, YELLOW_WOOL=144, GREEN_WOOL=145,
  RED_WOOL=146, BLACK_WOOL=147, BLUE_WOOL=148, PURPLE_WOOL=149,
  CYAN_WOOL=150, PINK_WOOL=151,

  // Stained glass
  WHITE_GLASS=152, RED_GLASS=153, ORANGE_GLASS=154, YELLOW_GLASS=155,
  GREEN_GLASS=156, BLUE_GLASS=157, PURPLE_GLASS=158, BLACK_GLASS=159,

  // Prismarine & Ocean
  PRISMARINE=160, DARK_PRISMARINE=161, PRISMARINE_BRICKS=162,
  SEA_LANTERN=163, CORAL_BLOCK=164, DEAD_CORAL=165,

  // Mushroom
  RED_MUSHROOM_BLOCK=166, BROWN_MUSHROOM_BLOCK=167, MUSHROOM_STEM=168,

  // Decorative
  BOOKSHELF=169, SPONGE=170, HAY_BALE=171, PUMPKIN=172, MELON=173,
  CACTUS=174, HONEYCOMB_BLOCK=175, SLIME_BLOCK=176, HONEY_BLOCK=177,
  POLISHED_BLACKSTONE=178,

  // Functional
  CRAFTING_TABLE=179, FURNACE=180, CHEST=181, ANVIL=182,
  ENCHANTING_TABLE=183, BOOKCASE_BLOCK=184, BEACON=185,
  RESPAWN_ANCHOR=186, LANTERN=187,

  // Sculk
  SCULK=188, SCULK_CATALYST=189, SCULK_SHRIEKER=190,

  // Copper
  EXPOSED_COPPER=191, WEATHERED_COPPER=192, OXIDIZED_COPPER=193,
  CUT_COPPER=194, GILDED_BLACKSTONE=195,

  // Deepslate variants
  DEEPSLATE_BRICKS=196, DEEPSLATE_TILES=197, TUFF_BRICKS=198,
  POLISHED_TUFF=199, CHISELED_DEEPSLATE=200,

  // Misc
  LAVA=201, SOUL_FIRE=202, NETHER_GOLD_ORE=203, AMETHYST_CLUSTER=204,
  POINTED_DRIPSTONE=205, JACK_O_LANTERN=206, LODESTONE=207,
  SMOOTH_QUARTZ=208, CHISELED_QUARTZ=209, NETHERITE_ORE=210,
  REINFORCED_DEEPSLATE=211, SPONGE_WET=212,

  // Fence/Wall style (solid blocks)
  COBBLE_WALL=213, NETHER_BRICK_FENCE=214, OAK_FENCE_BLOCK=215,

  // Extra natural
  DRIPSTONE_BLOCK=216, ROOTED_GRASS=217, SEAGRASS_BLOCK=218,
  KELP_BLOCK=219, LILY_PAD=220,

  // More
  LAPIS_BLOCK_DARK=221, IRON_BARS=222, CHAIN_BLOCK=223,
  TARGET_BLOCK=224, RAW_STONE=225,
}

const h = (hex: number): [number,number,number] => [(hex>>16&255)/255, (hex>>8&255)/255, (hex&255)/255];

export const BLOCK_COLORS: Record<number, [number,number,number]> = {
  [BlockType.AIR]:        h(0x000000),
  [BlockType.GRASS]:      h(0x567D46),
  [BlockType.DIRT]:       h(0x8B6914),
  [BlockType.STONE]:      h(0x808080),
  [BlockType.BEDROCK]:    h(0x2d2d2d),
  [BlockType.WOOD]:       h(0x6B4423),
  [BlockType.LEAF]:       h(0x228B22),
  [BlockType.SAND]:       h(0xF4D04E),
  [BlockType.WATER]:      h(0x4169E1),
  [BlockType.COAL_ORE]:   h(0x3a3a3a),
  [BlockType.IRON_ORE]:   h(0x8B7355),
  [BlockType.GLASS]:      h(0xadd8e6),
  [BlockType.PLANKS]:     h(0xDEB887),
  [BlockType.COBBLESTONE]:h(0x9e9e9e),
  [BlockType.TNT]:        h(0xff4444),
  [BlockType.GRANITE]:    h(0xBD9A7A),
  [BlockType.GRANITE_SMOOTH]: h(0xC9A88C),
  [BlockType.DIORITE]:    h(0xE0E0DC),
  [BlockType.DIORITE_SMOOTH]: h(0xECECE8),
  [BlockType.ANDESITE]:   h(0x7a7a78),
  [BlockType.ANDESITE_SMOOTH]: h(0x888886),
  [BlockType.DEEPSLATE]:  h(0x4a4a55),
  [BlockType.COBBLED_DEEPSLATE]: h(0x515157),
  [BlockType.TUFF]:       h(0x6D7059),
  [BlockType.CALCITE]:    h(0xE8E2D0),
  [BlockType.SMOOTH_STONE]: h(0x909090),
  [BlockType.STONE_BRICKS]: h(0x767676),
  [BlockType.MOSSY_STONE_BRICKS]: h(0x617A5B),
  [BlockType.CRACKED_STONE_BRICKS]: h(0x6E6E6E),
  [BlockType.CHISELED_STONE_BRICKS]: h(0x7D7D7D),
  [BlockType.BRICKS]:     h(0xB5623C),
  [BlockType.MOSSY_COBBLESTONE]: h(0x5E7556),
  [BlockType.POLISHED_GRANITE]: h(0xC8A882),
  [BlockType.POLISHED_DIORITE]: h(0xE8E8E4),
  [BlockType.POLISHED_ANDESITE]: h(0x888886),
  [BlockType.OAK_LOG]:    h(0x6B4423),
  [BlockType.BIRCH_LOG]:  h(0xD0C89A),
  [BlockType.SPRUCE_LOG]: h(0x4A3420),
  [BlockType.DARK_OAK_LOG]: h(0x3B2A15),
  [BlockType.JUNGLE_LOG]: h(0x7B5E33),
  [BlockType.ACACIA_LOG]: h(0xB0652A),
  [BlockType.STRIPPED_OAK_LOG]: h(0xC4A45A),
  [BlockType.BAMBOO_BLOCK]: h(0x8FA83B),
  [BlockType.BIRCH_PLANKS]: h(0xE8D9A2),
  [BlockType.SPRUCE_PLANKS]: h(0xA8804A),
  [BlockType.DARK_OAK_PLANKS]: h(0x4A3018),
  [BlockType.JUNGLE_PLANKS]: h(0xB8885A),
  [BlockType.ACACIA_PLANKS]: h(0xBA6E3E),
  [BlockType.BAMBOO_PLANKS]: h(0xD4B870),
  [BlockType.BIRCH_LEAF]: h(0x98C870),
  [BlockType.SPRUCE_LEAF]: h(0x3A6630),
  [BlockType.DARK_OAK_LEAF]: h(0x1E5228),
  [BlockType.JUNGLE_LEAF]: h(0x2E8B22),
  [BlockType.ACACIA_LEAF]: h(0x6B8E23),
  [BlockType.AZALEA_LEAF]: h(0x4D7E44),
  [BlockType.GOLD_ORE]:   h(0xFFC84A),
  [BlockType.DIAMOND_ORE]: h(0x50D9D8),
  [BlockType.EMERALD_ORE]: h(0x50D070),
  [BlockType.LAPIS_ORE]:  h(0x3050A0),
  [BlockType.REDSTONE_ORE]: h(0xC03020),
  [BlockType.COPPER_ORE]: h(0xB87D4A),
  [BlockType.ANCIENT_DEBRIS]: h(0x5C3A28),
  [BlockType.DIAMOND_DEEPSLATE]: h(0x4EB8B5),
  [BlockType.GOLD_DEEPSLATE]: h(0xD4A040),
  [BlockType.IRON_BLOCK]: h(0xD8D8D8),
  [BlockType.GOLD_BLOCK]: h(0xFAD340),
  [BlockType.DIAMOND_BLOCK]: h(0x5ADFDE),
  [BlockType.EMERALD_BLOCK]: h(0x17DD62),
  [BlockType.COPPER_BLOCK]: h(0xC2764D),
  [BlockType.COAL_BLOCK]: h(0x1A1A1A),
  [BlockType.LAPIS_BLOCK]: h(0x1845A0),
  [BlockType.REDSTONE_BLOCK]: h(0xD32020),
  [BlockType.AMETHYST_BLOCK]: h(0x9B6DB5),
  [BlockType.RAW_IRON_BLOCK]: h(0xB8977A),
  [BlockType.RAW_GOLD_BLOCK]: h(0xE0B855),
  [BlockType.RAW_COPPER_BLOCK]: h(0xB8723A),
  [BlockType.NETHERITE_BLOCK]: h(0x3C3640),
  [BlockType.QUARTZ_BLOCK]: h(0xE8E2D8),
  [BlockType.GRAVEL]:     h(0x908080),
  [BlockType.CLAY]:       h(0x9AAABA),
  [BlockType.MUD]:        h(0x5A4838),
  [BlockType.PODZOL]:     h(0x5E4519),
  [BlockType.MYCELIUM]:   h(0x8B738C),
  [BlockType.COARSE_DIRT]: h(0x7A5818),
  [BlockType.ROOTED_DIRT]: h(0x6E4F14),
  [BlockType.SOUL_SOIL]:  h(0x524030),
  [BlockType.MOSS_BLOCK]: h(0x4A6840),
  [BlockType.SANDSTONE]:  h(0xC8B860),
  [BlockType.SANDSTONE_SMOOTH]: h(0xD4C46C),
  [BlockType.SANDSTONE_CHISELED]: h(0xDCC870),
  [BlockType.RED_SAND]:   h(0xB85A28),
  [BlockType.RED_SANDSTONE]: h(0xA04A20),
  [BlockType.RED_SANDSTONE_SMOOTH]: h(0xAC5225),
  [BlockType.TERRACOTTA]: h(0x9E5F3A),
  [BlockType.WHITE_TERRACOTTA]: h(0xD0BAA8),
  [BlockType.ORANGE_TERRACOTTA]: h(0xA8581A),
  [BlockType.YELLOW_TERRACOTTA]: h(0xC8A020),
  [BlockType.RED_TERRACOTTA]: h(0x8E3828),
  [BlockType.BROWN_TERRACOTTA]: h(0x6E3A20),
  [BlockType.GRAY_TERRACOTTA]: h(0x656262),
  [BlockType.CYAN_TERRACOTTA]: h(0x546E72),
  [BlockType.ICE]:        h(0x90C0E0),
  [BlockType.PACKED_ICE]: h(0x7AB0D4),
  [BlockType.BLUE_ICE]:   h(0x5898C8),
  [BlockType.SNOW_BLOCK]: h(0xF0F0F4),
  [BlockType.NETHERRACK]: h(0x881111),
  [BlockType.SOUL_SAND]:  h(0x5A4438),
  [BlockType.GLOWSTONE]:  h(0xFFCC44),
  [BlockType.NETHER_BRICKS]: h(0x3A1420),
  [BlockType.RED_NETHER_BRICKS]: h(0x6A1828),
  [BlockType.BASALT]:     h(0x484848),
  [BlockType.BLACKSTONE]: h(0x282828),
  [BlockType.MAGMA]:      h(0xFF5500),
  [BlockType.CRYING_OBSIDIAN]: h(0x2A0858),
  [BlockType.NYLIUM_WARPED]: h(0x2A7A72),
  [BlockType.NYLIUM_CRIMSON]: h(0x8A1040),
  [BlockType.NETHER_WART_BLOCK]: h(0x880020),
  [BlockType.WARPED_STEM]: h(0x2A8070),
  [BlockType.CRIMSON_STEM]: h(0x8A1C30),
  [BlockType.WARPED_PLANKS]: h(0x2D8878),
  [BlockType.CRIMSON_PLANKS]: h(0x7A1C28),
  [BlockType.SHROOMLIGHT]: h(0xFFB840),
  [BlockType.END_STONE]:  h(0xD8D0A0),
  [BlockType.END_STONE_BRICKS]: h(0xD4CC98),
  [BlockType.PURPUR_BLOCK]: h(0x8B5E8B),
  [BlockType.PURPUR_PILLAR]: h(0x9068A0),
  [BlockType.OBSIDIAN]:   h(0x1A0A2A),
  [BlockType.WHITE_CONCRETE]:  h(0xCFCFCF),
  [BlockType.ORANGE_CONCRETE]: h(0xE07020),
  [BlockType.MAGENTA_CONCRETE]: h(0xBD44BD),
  [BlockType.LIGHT_BLUE_CONCRETE]: h(0x3AB3DA),
  [BlockType.YELLOW_CONCRETE]: h(0xF9C629),
  [BlockType.LIME_CONCRETE]: h(0x5EA918),
  [BlockType.PINK_CONCRETE]: h(0xF38BAA),
  [BlockType.GRAY_CONCRETE]: h(0x4C4C4C),
  [BlockType.CYAN_CONCRETE]: h(0x169C9C),
  [BlockType.PURPLE_CONCRETE]: h(0x642882),
  [BlockType.BLUE_CONCRETE]: h(0x3C44AA),
  [BlockType.BROWN_CONCRETE]: h(0x825432),
  [BlockType.GREEN_CONCRETE]: h(0x5E7C16),
  [BlockType.RED_CONCRETE]: h(0x8E2020),
  [BlockType.BLACK_CONCRETE]: h(0x080A0F),
  [BlockType.WHITE_WOOL]: h(0xE4E4E4),
  [BlockType.ORANGE_WOOL]: h(0xF07820),
  [BlockType.YELLOW_WOOL]: h(0xF8D528),
  [BlockType.GREEN_WOOL]: h(0x5A8C18),
  [BlockType.RED_WOOL]:   h(0xA42020),
  [BlockType.BLACK_WOOL]: h(0x141414),
  [BlockType.BLUE_WOOL]:  h(0x3030A8),
  [BlockType.PURPLE_WOOL]: h(0x7030A0),
  [BlockType.CYAN_WOOL]:  h(0x149090),
  [BlockType.PINK_WOOL]:  h(0xF498A8),
  [BlockType.WHITE_GLASS]: h(0xE8E8E8),
  [BlockType.RED_GLASS]:  h(0xA03030),
  [BlockType.ORANGE_GLASS]: h(0xC06820),
  [BlockType.YELLOW_GLASS]: h(0xC8B820),
  [BlockType.GREEN_GLASS]: h(0x307830),
  [BlockType.BLUE_GLASS]: h(0x303898),
  [BlockType.PURPLE_GLASS]: h(0x682882),
  [BlockType.BLACK_GLASS]: h(0x101010),
  [BlockType.PRISMARINE]: h(0x5E9A8A),
  [BlockType.DARK_PRISMARINE]: h(0x2E6258),
  [BlockType.PRISMARINE_BRICKS]: h(0x6EA898),
  [BlockType.SEA_LANTERN]: h(0xA8D8D4),
  [BlockType.CORAL_BLOCK]: h(0xE84080),
  [BlockType.DEAD_CORAL]: h(0x787068),
  [BlockType.RED_MUSHROOM_BLOCK]: h(0xCC2020),
  [BlockType.BROWN_MUSHROOM_BLOCK]: h(0x986030),
  [BlockType.MUSHROOM_STEM]: h(0xD8D0C0),
  [BlockType.BOOKSHELF]:  h(0xC89450),
  [BlockType.SPONGE]:     h(0xC8C820),
  [BlockType.HAY_BALE]:   h(0xD4B840),
  [BlockType.PUMPKIN]:    h(0xE07020),
  [BlockType.MELON]:      h(0x78A828),
  [BlockType.CACTUS]:     h(0x3A7A28),
  [BlockType.HONEYCOMB_BLOCK]: h(0xE89020),
  [BlockType.SLIME_BLOCK]: h(0x60B840),
  [BlockType.HONEY_BLOCK]: h(0xE8A820),
  [BlockType.POLISHED_BLACKSTONE]: h(0x303030),
  [BlockType.CRAFTING_TABLE]: h(0x8B6428),
  [BlockType.FURNACE]:    h(0x787878),
  [BlockType.CHEST]:      h(0xC09040),
  [BlockType.ANVIL]:      h(0x484848),
  [BlockType.ENCHANTING_TABLE]: h(0x880020),
  [BlockType.BOOKCASE_BLOCK]: h(0xB88040),
  [BlockType.BEACON]:     h(0x80FFD0),
  [BlockType.RESPAWN_ANCHOR]: h(0x2040C8),
  [BlockType.LANTERN]:    h(0xFFD040),
  [BlockType.SCULK]:      h(0x0A2030),
  [BlockType.SCULK_CATALYST]: h(0x102840),
  [BlockType.SCULK_SHRIEKER]: h(0x142850),
  [BlockType.EXPOSED_COPPER]: h(0xBD8A6A),
  [BlockType.WEATHERED_COPPER]: h(0x709C70),
  [BlockType.OXIDIZED_COPPER]: h(0x52A888),
  [BlockType.CUT_COPPER]: h(0xBE7A48),
  [BlockType.GILDED_BLACKSTONE]: h(0x3A2808),
  [BlockType.DEEPSLATE_BRICKS]: h(0x3E3E48),
  [BlockType.DEEPSLATE_TILES]: h(0x343440),
  [BlockType.TUFF_BRICKS]: h(0x787060),
  [BlockType.POLISHED_TUFF]: h(0x747060),
  [BlockType.CHISELED_DEEPSLATE]: h(0x404048),
  [BlockType.LAVA]:       h(0xFF4400),
  [BlockType.SOUL_FIRE]:  h(0x00A0D0),
  [BlockType.NETHER_GOLD_ORE]: h(0xD4A820),
  [BlockType.AMETHYST_CLUSTER]: h(0xB080D8),
  [BlockType.POINTED_DRIPSTONE]: h(0x9A8060),
  [BlockType.JACK_O_LANTERN]: h(0xF09000),
  [BlockType.LODESTONE]:  h(0x707880),
  [BlockType.SMOOTH_QUARTZ]: h(0xECE6DC),
  [BlockType.CHISELED_QUARTZ]: h(0xE8E0D4),
  [BlockType.NETHERITE_ORE]: h(0x382830),
  [BlockType.REINFORCED_DEEPSLATE]: h(0x303038),
  [BlockType.SPONGE_WET]: h(0xA8A820),
  [BlockType.COBBLE_WALL]: h(0x909090),
  [BlockType.NETHER_BRICK_FENCE]: h(0x3A1420),
  [BlockType.OAK_FENCE_BLOCK]: h(0xC4A450),
  [BlockType.DRIPSTONE_BLOCK]: h(0x907860),
  [BlockType.ROOTED_GRASS]: h(0x5E9040),
  [BlockType.SEAGRASS_BLOCK]: h(0x285840),
  [BlockType.KELP_BLOCK]: h(0x2A6830),
  [BlockType.LILY_PAD]:   h(0x287828),
  [BlockType.LAPIS_BLOCK_DARK]: h(0x102060),
  [BlockType.IRON_BARS]:  h(0x808888),
  [BlockType.CHAIN_BLOCK]: h(0x505858),
  [BlockType.TARGET_BLOCK]: h(0xD03028),
  [BlockType.RAW_STONE]:  h(0x888888),
};

export const BLOCK_NAMES: Record<number, string> = {
  [BlockType.AIR]:'Air',[BlockType.GRASS]:'Grass',[BlockType.DIRT]:'Dirt',
  [BlockType.STONE]:'Stone',[BlockType.BEDROCK]:'Bedrock',[BlockType.WOOD]:'Oak Wood',
  [BlockType.LEAF]:'Oak Leaves',[BlockType.SAND]:'Sand',[BlockType.WATER]:'Water',
  [BlockType.COAL_ORE]:'Coal Ore',[BlockType.IRON_ORE]:'Iron Ore',[BlockType.GLASS]:'Glass',
  [BlockType.PLANKS]:'Oak Planks',[BlockType.COBBLESTONE]:'Cobblestone',[BlockType.TNT]:'TNT',
  [BlockType.GRANITE]:'Granite',[BlockType.GRANITE_SMOOTH]:'Polished Granite',[BlockType.DIORITE]:'Diorite',
  [BlockType.DIORITE_SMOOTH]:'Polished Diorite',[BlockType.ANDESITE]:'Andesite',[BlockType.ANDESITE_SMOOTH]:'Polished Andesite',
  [BlockType.DEEPSLATE]:'Deepslate',[BlockType.COBBLED_DEEPSLATE]:'Cobbled Deepslate',[BlockType.TUFF]:'Tuff',
  [BlockType.CALCITE]:'Calcite',[BlockType.SMOOTH_STONE]:'Smooth Stone',[BlockType.STONE_BRICKS]:'Stone Bricks',
  [BlockType.MOSSY_STONE_BRICKS]:'Mossy Stone Bricks',[BlockType.CRACKED_STONE_BRICKS]:'Cracked Stone Bricks',
  [BlockType.CHISELED_STONE_BRICKS]:'Chiseled Stone Bricks',[BlockType.BRICKS]:'Bricks',
  [BlockType.MOSSY_COBBLESTONE]:'Mossy Cobblestone',[BlockType.POLISHED_GRANITE]:'Polished Granite',
  [BlockType.POLISHED_DIORITE]:'Polished Diorite',[BlockType.POLISHED_ANDESITE]:'Polished Andesite',
  [BlockType.OAK_LOG]:'Oak Log',[BlockType.BIRCH_LOG]:'Birch Log',[BlockType.SPRUCE_LOG]:'Spruce Log',
  [BlockType.DARK_OAK_LOG]:'Dark Oak Log',[BlockType.JUNGLE_LOG]:'Jungle Log',[BlockType.ACACIA_LOG]:'Acacia Log',
  [BlockType.STRIPPED_OAK_LOG]:'Stripped Oak Log',[BlockType.BAMBOO_BLOCK]:'Bamboo Block',
  [BlockType.BIRCH_PLANKS]:'Birch Planks',[BlockType.SPRUCE_PLANKS]:'Spruce Planks',
  [BlockType.DARK_OAK_PLANKS]:'Dark Oak Planks',[BlockType.JUNGLE_PLANKS]:'Jungle Planks',
  [BlockType.ACACIA_PLANKS]:'Acacia Planks',[BlockType.BAMBOO_PLANKS]:'Bamboo Planks',
  [BlockType.BIRCH_LEAF]:'Birch Leaves',[BlockType.SPRUCE_LEAF]:'Spruce Leaves',
  [BlockType.DARK_OAK_LEAF]:'Dark Oak Leaves',[BlockType.JUNGLE_LEAF]:'Jungle Leaves',
  [BlockType.ACACIA_LEAF]:'Acacia Leaves',[BlockType.AZALEA_LEAF]:'Azalea Leaves',
  [BlockType.GOLD_ORE]:'Gold Ore',[BlockType.DIAMOND_ORE]:'Diamond Ore',
  [BlockType.EMERALD_ORE]:'Emerald Ore',[BlockType.LAPIS_ORE]:'Lapis Ore',
  [BlockType.REDSTONE_ORE]:'Redstone Ore',[BlockType.COPPER_ORE]:'Copper Ore',
  [BlockType.ANCIENT_DEBRIS]:'Ancient Debris',[BlockType.DIAMOND_DEEPSLATE]:'Diamond Deepslate Ore',
  [BlockType.GOLD_DEEPSLATE]:'Gold Deepslate Ore',
  [BlockType.IRON_BLOCK]:'Iron Block',[BlockType.GOLD_BLOCK]:'Gold Block',
  [BlockType.DIAMOND_BLOCK]:'Diamond Block',[BlockType.EMERALD_BLOCK]:'Emerald Block',
  [BlockType.COPPER_BLOCK]:'Copper Block',[BlockType.COAL_BLOCK]:'Coal Block',
  [BlockType.LAPIS_BLOCK]:'Lapis Block',[BlockType.REDSTONE_BLOCK]:'Redstone Block',
  [BlockType.AMETHYST_BLOCK]:'Amethyst Block',[BlockType.RAW_IRON_BLOCK]:'Raw Iron Block',
  [BlockType.RAW_GOLD_BLOCK]:'Raw Gold Block',[BlockType.RAW_COPPER_BLOCK]:'Raw Copper Block',
  [BlockType.NETHERITE_BLOCK]:'Netherite Block',[BlockType.QUARTZ_BLOCK]:'Quartz Block',
  [BlockType.GRAVEL]:'Gravel',[BlockType.CLAY]:'Clay',[BlockType.MUD]:'Mud',
  [BlockType.PODZOL]:'Podzol',[BlockType.MYCELIUM]:'Mycelium',[BlockType.COARSE_DIRT]:'Coarse Dirt',
  [BlockType.ROOTED_DIRT]:'Rooted Dirt',[BlockType.SOUL_SOIL]:'Soul Soil',[BlockType.MOSS_BLOCK]:'Moss Block',
  [BlockType.SANDSTONE]:'Sandstone',[BlockType.SANDSTONE_SMOOTH]:'Smooth Sandstone',
  [BlockType.SANDSTONE_CHISELED]:'Chiseled Sandstone',[BlockType.RED_SAND]:'Red Sand',
  [BlockType.RED_SANDSTONE]:'Red Sandstone',[BlockType.RED_SANDSTONE_SMOOTH]:'Smooth Red Sandstone',
  [BlockType.TERRACOTTA]:'Terracotta',[BlockType.WHITE_TERRACOTTA]:'White Terracotta',
  [BlockType.ORANGE_TERRACOTTA]:'Orange Terracotta',[BlockType.YELLOW_TERRACOTTA]:'Yellow Terracotta',
  [BlockType.RED_TERRACOTTA]:'Red Terracotta',[BlockType.BROWN_TERRACOTTA]:'Brown Terracotta',
  [BlockType.GRAY_TERRACOTTA]:'Gray Terracotta',[BlockType.CYAN_TERRACOTTA]:'Cyan Terracotta',
  [BlockType.ICE]:'Ice',[BlockType.PACKED_ICE]:'Packed Ice',[BlockType.BLUE_ICE]:'Blue Ice',
  [BlockType.SNOW_BLOCK]:'Snow Block',[BlockType.NETHERRACK]:'Netherrack',[BlockType.SOUL_SAND]:'Soul Sand',
  [BlockType.GLOWSTONE]:'Glowstone',[BlockType.NETHER_BRICKS]:'Nether Bricks',
  [BlockType.RED_NETHER_BRICKS]:'Red Nether Bricks',[BlockType.BASALT]:'Basalt',
  [BlockType.BLACKSTONE]:'Blackstone',[BlockType.MAGMA]:'Magma Block',
  [BlockType.CRYING_OBSIDIAN]:'Crying Obsidian',[BlockType.NYLIUM_WARPED]:'Warped Nylium',
  [BlockType.NYLIUM_CRIMSON]:'Crimson Nylium',[BlockType.NETHER_WART_BLOCK]:'Nether Wart Block',
  [BlockType.WARPED_STEM]:'Warped Stem',[BlockType.CRIMSON_STEM]:'Crimson Stem',
  [BlockType.WARPED_PLANKS]:'Warped Planks',[BlockType.CRIMSON_PLANKS]:'Crimson Planks',
  [BlockType.SHROOMLIGHT]:'Shroomlight',[BlockType.END_STONE]:'End Stone',
  [BlockType.END_STONE_BRICKS]:'End Stone Bricks',[BlockType.PURPUR_BLOCK]:'Purpur Block',
  [BlockType.PURPUR_PILLAR]:'Purpur Pillar',[BlockType.OBSIDIAN]:'Obsidian',
  [BlockType.WHITE_CONCRETE]:'White Concrete',[BlockType.ORANGE_CONCRETE]:'Orange Concrete',
  [BlockType.MAGENTA_CONCRETE]:'Magenta Concrete',[BlockType.LIGHT_BLUE_CONCRETE]:'Light Blue Concrete',
  [BlockType.YELLOW_CONCRETE]:'Yellow Concrete',[BlockType.LIME_CONCRETE]:'Lime Concrete',
  [BlockType.PINK_CONCRETE]:'Pink Concrete',[BlockType.GRAY_CONCRETE]:'Gray Concrete',
  [BlockType.CYAN_CONCRETE]:'Cyan Concrete',[BlockType.PURPLE_CONCRETE]:'Purple Concrete',
  [BlockType.BLUE_CONCRETE]:'Blue Concrete',[BlockType.BROWN_CONCRETE]:'Brown Concrete',
  [BlockType.GREEN_CONCRETE]:'Green Concrete',[BlockType.RED_CONCRETE]:'Red Concrete',
  [BlockType.BLACK_CONCRETE]:'Black Concrete',
  [BlockType.WHITE_WOOL]:'White Wool',[BlockType.ORANGE_WOOL]:'Orange Wool',
  [BlockType.YELLOW_WOOL]:'Yellow Wool',[BlockType.GREEN_WOOL]:'Green Wool',
  [BlockType.RED_WOOL]:'Red Wool',[BlockType.BLACK_WOOL]:'Black Wool',
  [BlockType.BLUE_WOOL]:'Blue Wool',[BlockType.PURPLE_WOOL]:'Purple Wool',
  [BlockType.CYAN_WOOL]:'Cyan Wool',[BlockType.PINK_WOOL]:'Pink Wool',
  [BlockType.WHITE_GLASS]:'White Stained Glass',[BlockType.RED_GLASS]:'Red Stained Glass',
  [BlockType.ORANGE_GLASS]:'Orange Stained Glass',[BlockType.YELLOW_GLASS]:'Yellow Stained Glass',
  [BlockType.GREEN_GLASS]:'Green Stained Glass',[BlockType.BLUE_GLASS]:'Blue Stained Glass',
  [BlockType.PURPLE_GLASS]:'Purple Stained Glass',[BlockType.BLACK_GLASS]:'Black Stained Glass',
  [BlockType.PRISMARINE]:'Prismarine',[BlockType.DARK_PRISMARINE]:'Dark Prismarine',
  [BlockType.PRISMARINE_BRICKS]:'Prismarine Bricks',[BlockType.SEA_LANTERN]:'Sea Lantern',
  [BlockType.CORAL_BLOCK]:'Coral Block',[BlockType.DEAD_CORAL]:'Dead Coral',
  [BlockType.RED_MUSHROOM_BLOCK]:'Red Mushroom Block',[BlockType.BROWN_MUSHROOM_BLOCK]:'Brown Mushroom Block',
  [BlockType.MUSHROOM_STEM]:'Mushroom Stem',[BlockType.BOOKSHELF]:'Bookshelf',
  [BlockType.SPONGE]:'Sponge',[BlockType.HAY_BALE]:'Hay Bale',[BlockType.PUMPKIN]:'Pumpkin',
  [BlockType.MELON]:'Melon',[BlockType.CACTUS]:'Cactus',[BlockType.HONEYCOMB_BLOCK]:'Honeycomb Block',
  [BlockType.SLIME_BLOCK]:'Slime Block',[BlockType.HONEY_BLOCK]:'Honey Block',
  [BlockType.POLISHED_BLACKSTONE]:'Polished Blackstone',[BlockType.CRAFTING_TABLE]:'Crafting Table',
  [BlockType.FURNACE]:'Furnace',[BlockType.CHEST]:'Chest',[BlockType.ANVIL]:'Anvil',
  [BlockType.ENCHANTING_TABLE]:'Enchanting Table',[BlockType.BOOKCASE_BLOCK]:'Bookcase',
  [BlockType.BEACON]:'Beacon',[BlockType.RESPAWN_ANCHOR]:'Respawn Anchor',[BlockType.LANTERN]:'Lantern',
  [BlockType.SCULK]:'Sculk',[BlockType.SCULK_CATALYST]:'Sculk Catalyst',[BlockType.SCULK_SHRIEKER]:'Sculk Shrieker',
  [BlockType.EXPOSED_COPPER]:'Exposed Copper',[BlockType.WEATHERED_COPPER]:'Weathered Copper',
  [BlockType.OXIDIZED_COPPER]:'Oxidized Copper',[BlockType.CUT_COPPER]:'Cut Copper',
  [BlockType.GILDED_BLACKSTONE]:'Gilded Blackstone',[BlockType.DEEPSLATE_BRICKS]:'Deepslate Bricks',
  [BlockType.DEEPSLATE_TILES]:'Deepslate Tiles',[BlockType.TUFF_BRICKS]:'Tuff Bricks',
  [BlockType.POLISHED_TUFF]:'Polished Tuff',[BlockType.CHISELED_DEEPSLATE]:'Chiseled Deepslate',
  [BlockType.LAVA]:'Lava',[BlockType.SOUL_FIRE]:'Soul Fire',[BlockType.NETHER_GOLD_ORE]:'Nether Gold Ore',
  [BlockType.AMETHYST_CLUSTER]:'Amethyst Cluster',[BlockType.POINTED_DRIPSTONE]:'Pointed Dripstone',
  [BlockType.JACK_O_LANTERN]:'Jack o Lantern',[BlockType.LODESTONE]:'Lodestone',
  [BlockType.SMOOTH_QUARTZ]:'Smooth Quartz',[BlockType.CHISELED_QUARTZ]:'Chiseled Quartz',
  [BlockType.NETHERITE_ORE]:'Netherite Ore',[BlockType.REINFORCED_DEEPSLATE]:'Reinforced Deepslate',
  [BlockType.SPONGE_WET]:'Wet Sponge',[BlockType.COBBLE_WALL]:'Cobblestone Wall',
  [BlockType.NETHER_BRICK_FENCE]:'Nether Brick Fence',[BlockType.OAK_FENCE_BLOCK]:'Oak Fence',
  [BlockType.DRIPSTONE_BLOCK]:'Dripstone Block',[BlockType.ROOTED_GRASS]:'Rooted Grass',
  [BlockType.SEAGRASS_BLOCK]:'Seagrass',[BlockType.KELP_BLOCK]:'Kelp Block',
  [BlockType.LILY_PAD]:'Lily Pad',[BlockType.LAPIS_BLOCK_DARK]:'Dark Lapis Block',
  [BlockType.IRON_BARS]:'Iron Bars',[BlockType.CHAIN_BLOCK]:'Chain',
  [BlockType.TARGET_BLOCK]:'Target',[BlockType.RAW_STONE]:'Raw Stone',
};

export function isSolid(type: BlockType): boolean {
  return type !== BlockType.AIR && type !== BlockType.WATER && type !== BlockType.LAVA;
}

export function isTransparent(type: BlockType): boolean {
  return (
    type === BlockType.AIR || type === BlockType.WATER || type === BlockType.LAVA ||
    type === BlockType.LEAF || type === BlockType.GLASS ||
    type === BlockType.BIRCH_LEAF || type === BlockType.SPRUCE_LEAF ||
    type === BlockType.DARK_OAK_LEAF || type === BlockType.JUNGLE_LEAF ||
    type === BlockType.ACACIA_LEAF || type === BlockType.AZALEA_LEAF ||
    type === BlockType.ICE || type === BlockType.PACKED_ICE || type === BlockType.BLUE_ICE ||
    type === BlockType.WHITE_GLASS || type === BlockType.RED_GLASS ||
    type === BlockType.ORANGE_GLASS || type === BlockType.YELLOW_GLASS ||
    type === BlockType.GREEN_GLASS || type === BlockType.BLUE_GLASS ||
    type === BlockType.PURPLE_GLASS || type === BlockType.BLACK_GLASS ||
    type === BlockType.SLIME_BLOCK || type === BlockType.HONEY_BLOCK
  );
}

export function isLightEmitting(type: BlockType): boolean {
  return type === BlockType.GLOWSTONE || type === BlockType.SEA_LANTERN ||
    type === BlockType.LANTERN || type === BlockType.SHROOMLIGHT ||
    type === BlockType.JACK_O_LANTERN || type === BlockType.BEACON ||
    type === BlockType.LAVA || type === BlockType.MAGMA || type === BlockType.SOUL_FIRE;
}

export const HOTBAR_CREATIVE: BlockType[] = [
  BlockType.GRASS, BlockType.STONE, BlockType.PLANKS, BlockType.SAND,
  BlockType.COBBLESTONE, BlockType.GRAVEL, BlockType.OAK_LOG, BlockType.GLASS,
  BlockType.CRAFTING_TABLE,
];

export const HOTBAR_SURVIVAL: BlockType[] = [
  BlockType.DIRT, BlockType.STONE, BlockType.PLANKS, BlockType.COBBLESTONE,
  BlockType.AIR, BlockType.AIR, BlockType.AIR, BlockType.AIR, BlockType.AIR,
];
